In [22]:
import pandas as pd
import sys

In [2]:
df = pd.read_csv(r"C:\Users\ASUS\Desktop\Amex\Amex_Campus_Challenge_Train.csv")

In [3]:
df

,ind_recommended,activation,customer_digital_activity_04,customer_spend_01,customer_industry_spend_01,customer_industry_spend_02,customer_industry_spend_03,customer_industry_spend_04,customer_industry_spend_05,customer_spend_02,...,merchant_spend_09,merchant_profile_03,customer_digital_activity_01,merchant_spend_10,customer_profile_03,customer_digital_activity_02,customer_profile_04,distance_05,customer,merchant
0,0,0,NaN,107.215862,26.686594,74.0,3682.75,138.0,111.0,14.0,...,49466.0,65923.0,0.000000,29.180000,58.434969,32.500000,86.0,15.856826,168972,152285
1,0,0,NaN,35.552000,50.928261,3.0,1171.35,23.0,17.0,2.0,...,3638.0,7801.0,0.419355,28.465000,5.392089,7.000000,125.0,6.998555,212404,39032
2,0,0,NaN,31.623103,48.837872,19.0,2295.38,47.0,42.0,11.0,...,3912.0,12868.0,0.836364,421.500000,33.780445,0.000000,180.0,1.753009,225178,7439
3,0,0,NaN,112.277391,NaN,NaN,NaN,NaN,NaN,16.0,...,28919.0,23553.0,0.952381,50.000000,37.340085,28.666667,134.0,9.000063,183948,485069
4,1,0,NaN,448.427273,NaN,NaN,NaN,NaN,NaN,5.0,...,1086.0,308.0,0.754386,69.509000,77.794164,15.000000,114.0,1.767939,210107,536004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12229973,0,1,10.0,41.706875,13.162500,9.0,368.55,28.0,19.0,5.0,...,7565.0,1171.0,NaN,17.568750,77.327287,3.166667,510.0,0.109332,23040,564879
12229974,0,1,NaN,55.781622,53.352927,5.0,2187.47,41.0,31.0,12.0,...,34355.0,9928.0,NaN,25.085000,93.590472,4.666667,543.0,2.651707,23087,453544
12229975,0,1,NaN,61.496000,107.744375,5.0,1723.91,16.0,10.0,13.0,...,1434.0,270.0,0.000000,85.285000,100.000000,4.666667,612.0,3.300739,23181,259023
12229976,0,1,NaN,117.348421,117.146939,15.0,5740.20,49.0,42.0,5.0,...,854.0,915.0,1.000000,46.081518,100.000000,8.666667,253.0,11.489237,23236,305617
12229977,0,1,NaN,77.012286,NaN,NaN,NaN,NaN,NaN,11.0,...,17708.0,50745.0,0.754717,49.115000,40.558968,11.000000,375.0,6.801716,23267,557003

In [21]:
df.isnull().sum()

ind_recommended                        0
activation                             0
customer_digital_activity_04    10757359
customer_spend_01                2047765
customer_industry_spend_01       5854184
                                  ...
customer_digital_activity_02       32878
customer_profile_04                 4111
distance_05                            0
customer                               0
merchant                               0
Length: 71, dtype: int64

In [4]:
df1 = pd.read_csv(r"C:\Users\ASUS\Desktop\Amex\Amex_Campus_Challenge_Eval_Round1.csv")

In [6]:
df1

,distance_05,customer_digital_activity_04,customer_spend_01,customer_industry_spend_01,customer_industry_spend_02,customer_industry_spend_03,customer_industry_spend_04,customer_industry_spend_05,customer_spend_02,customer_spend_03,...,merchant_profile_02,merchant_spend_09,merchant_profile_03,customer_digital_activity_01,merchant_spend_10,customer_profile_03,customer_digital_activity_02,customer_profile_04,customer,merchant
0,1.621171,NaN,112.334000,80.552500,9.0,966.63,12.0,10.0,4.0,41.0,...,0.437500,26299.0,4777.0,0.800000,33.300,72.268283,7.000000,423.0,467915,599167
1,2.441944,NaN,112.334000,NaN,NaN,NaN,NaN,NaN,4.0,41.0,...,0.397059,7122.0,4803.0,0.800000,793.290,72.268283,7.000000,423.0,467915,686617
2,2.438082,NaN,112.334000,71.192500,3.0,284.77,4.0,4.0,4.0,41.0,...,NaN,7222.0,14860.0,0.800000,100.000,72.268283,7.000000,423.0,467915,829193
3,2.072182,NaN,112.334000,NaN,NaN,NaN,NaN,NaN,4.0,41.0,...,0.142857,11410.0,11968.0,0.800000,252.380,72.268283,7.000000,423.0,467915,1077034
4,2.380853,NaN,302.792500,NaN,NaN,NaN,NaN,NaN,3.0,37.0,...,0.100000,1847.0,5842.0,0.800000,87.500,72.268283,7.000000,423.0,467915,876647
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8496461,22.197181,NaN,65.181875,171.463500,8.0,3429.27,20.0,16.0,21.0,94.0,...,NaN,25017.0,29209.0,0.000000,49.500,92.116548,1.666667,270.0,464447,644485
8496462,17.812486,NaN,15.680000,11.095556,5.0,99.86,9.0,8.0,2.0,14.0,...,0.452830,39731.0,3529.0,0.733333,32.440,34.500012,0.166667,24.0,522564,802309
8496463,8.299482,NaN,61.723409,NaN,NaN,NaN,NaN,NaN,11.0,112.0,...,0.270833,2994.0,7534.0,1.000000,198.500,50.484705,0.166667,390.0,465030,741321
8496464,4.665418,NaN,270.908125,31.177692,4.0,405.31,13.0,6.0,10.0,28.0,...,0.250000,423.0,241.0,0.916667,33.000,86.240872,0.333333,310.0,495259,625845
8496465,23.137716,1.0,1152.836371,80.190000,1.0,80.19,1.0,1.0,28.0,134.0,...,0.243902,8573.0,4374.0,0.200000,23.625,100.000000,7.333333,34.0,556241,639032

In [23]:
df1.isnull().sum()

distance_05                           0
customer_digital_activity_04    6812136
customer_spend_01               1417169
customer_industry_spend_01      3726131
customer_industry_spend_02      3726131
                                 ...
customer_profile_03              688796
customer_digital_activity_02     639548
customer_profile_04              575780
customer                              0
merchant                              0
Length: 69, dtype: int64

In [10]:
df.columns

Index(['ind_recommended', 'activation', 'customer_digital_activity_04',
       'customer_spend_01', 'customer_industry_spend_01',
       'customer_industry_spend_02', 'customer_industry_spend_03',
       'customer_industry_spend_04', 'customer_industry_spend_05',
       'customer_spend_02', 'customer_spend_03', 'customer_merchant_02',
       'customer_merchant_01', 'customer_spend_04', 'customer_spend_05',
       'customer_spend_06', 'customer_spend_07', 'merchant_spend_01',
       'merchant_spend_02', 'merchant_spend_03', 'merchant_spend_04',
       'merchant_spend_05', 'merchant_spend_06', 'merchant_spend_07',
       'merchant_spend_08', 'merchant_profile_01', 'customer_merchant_03',
       'customer_profile_01', 'customer_profile_02',
       'customer_digital_activity_05', 'customer_spend_13',
       'customer_digital_activity_06', 'customer_spend_14',
       'customer_digital_activity_07', 'customer_digital_activity_08',
       'customer_digital_activity_09', 'customer_digital_activity_10',
       'customer_digital_activity_11', 'customer_digital_activity_12',
       'customer_digital_activity_13', 'customer_digital_activity_14',
       'customer_digital_activity_15', 'customer_spend_15',
       'customer_digital_activity_16', 'customer_spend_16',
       'customer_spend_17', 'customer_digital_activity_17',
       'customer_digital_activity_03', 'merchant_spend_11',
       'customer_digital_activity_18', 'customer_digital_activity_19',
       'distance_01', 'customer_digital_activity_20', 'distance_02',
       'distance_03', 'customer_spend_18', 'customer_spend_19',
       'customer_digital_activity_21', 'customer_digital_activity_22',
       'distance_04', 'merchant_profile_02', 'merchant_spend_09',
       'merchant_profile_03', 'customer_digital_activity_01',
       'merchant_spend_10', 'customer_profile_03',
       'customer_digital_activity_02', 'customer_profile_04', 'distance_05',
       'customer', 'merchant'],
      dtype='object')

In [11]:
df1.columns

Index(['distance_05', 'customer_digital_activity_04', 'customer_spend_01',
       'customer_industry_spend_01', 'customer_industry_spend_02',
       'customer_industry_spend_03', 'customer_industry_spend_04',
       'customer_industry_spend_05', 'customer_spend_02', 'customer_spend_03',
       'customer_merchant_02', 'customer_merchant_01', 'customer_spend_04',
       'customer_spend_05', 'customer_spend_06', 'customer_spend_07',
       'merchant_spend_01', 'merchant_spend_02', 'merchant_spend_03',
       'merchant_spend_04', 'merchant_spend_05', 'merchant_spend_06',
       'merchant_spend_07', 'merchant_spend_08', 'merchant_profile_01',
       'customer_merchant_03', 'customer_profile_01', 'customer_profile_02',
       'customer_digital_activity_05', 'customer_spend_13',
       'customer_digital_activity_06', 'customer_spend_14',
       'customer_digital_activity_07', 'customer_digital_activity_08',
       'customer_digital_activity_09', 'customer_digital_activity_10',
       'customer_digital_activity_11', 'customer_digital_activity_12',
       'customer_digital_activity_13', 'customer_digital_activity_14',
       'customer_digital_activity_15', 'customer_spend_15',
       'customer_digital_activity_16', 'customer_spend_16',
       'customer_spend_17', 'customer_digital_activity_17',
       'customer_digital_activity_03', 'merchant_spend_11',
       'customer_digital_activity_18', 'customer_digital_activity_19',
       'distance_01', 'customer_digital_activity_20', 'distance_02',
       'distance_03', 'customer_spend_18', 'customer_spend_19',
       'customer_digital_activity_21', 'customer_digital_activity_22',
       'distance_04', 'merchant_profile_02', 'merchant_spend_09',
       'merchant_profile_03', 'customer_digital_activity_01',
       'merchant_spend_10', 'customer_profile_03',
       'customer_digital_activity_02', 'customer_profile_04', 'customer',
       'merchant'],
      dtype='object')

In [30]:
a = []
b = []

for i in df.columns:
    a.append(i)
for j in df1.columns:
    b.append(j)
print(a)
print(b)

for i in a:
    if(i not in b):
        print(i)

['ind_recommended', 'activation', 'customer_digital_activity_04', 'customer_spend_01', 'customer_industry_spend_01', 'customer_industry_spend_02', 'customer_industry_spend_03', 'customer_industry_spend_04', 'customer_industry_spend_05', 'customer_spend_02', 'customer_spend_03', 'customer_merchant_02', 'customer_merchant_01', 'customer_spend_04', 'customer_spend_05', 'customer_spend_06', 'customer_spend_07', 'merchant_spend_01', 'merchant_spend_02', 'merchant_spend_03', 'merchant_spend_04', 'merchant_spend_05', 'merchant_spend_06', 'merchant_spend_07', 'merchant_spend_08', 'merchant_profile_01', 'customer_merchant_03', 'customer_profile_01', 'customer_profile_02', 'customer_digital_activity_05', 'customer_spend_13', 'customer_digital_activity_06', 'customer_spend_14', 'customer_digital_activity_07', 'customer_digital_activity_08', 'customer_digital_activity_09', 'customer_digital_activity_10', 'customer_digital_activity_11', 'customer_digital_activity_12', 'customer_digital_activity_13', 'customer_digital_activity_14', 'customer_digital_activity_15', 'customer_spend_15', 'customer_digital_activity_16', 'customer_spend_16', 'customer_spend_17', 'customer_digital_activity_17', 'customer_digital_activity_03', 'merchant_spend_11', 'customer_digital_activity_18', 'customer_digital_activity_19', 'distance_01', 'customer_digital_activity_20', 'distance_02', 'distance_03', 'customer_spend_18', 'customer_spend_19', 'customer_digital_activity_21', 'customer_digital_activity_22', 'distance_04', 'merchant_profile_02', 'merchant_spend_09', 'merchant_profile_03', 'customer_digital_activity_01', 'merchant_spend_10', 'customer_profile_03', 'customer_digital_activity_02', 'customer_profile_04', 'distance_05', 'customer', 'merchant']
['distance_05', 'customer_digital_activity_04', 'customer_spend_01', 'customer_industry_spend_01', 'customer_industry_spend_02', 'customer_industry_spend_03', 'customer_industry_spend_04', 'customer_industry_spend_05', 'customer_spend_02', 'customer_spend_03', 'customer_merchant_02', 'customer_merchant_01', 'customer_spend_04', 'customer_spend_05', 'customer_spend_06', 'customer_spend_07', 'merchant_spend_01', 'merchant_spend_02', 'merchant_spend_03', 'merchant_spend_04', 'merchant_spend_05', 'merchant_spend_06', 'merchant_spend_07', 'merchant_spend_08', 'merchant_profile_01', 'customer_merchant_03', 'customer_profile_01', 'customer_profile_02', 'customer_digital_activity_05', 'customer_spend_13', 'customer_digital_activity_06', 'customer_spend_14', 'customer_digital_activity_07', 'customer_digital_activity_08', 'customer_digital_activity_09', 'customer_digital_activity_10', 'customer_digital_activity_11', 'customer_digital_activity_12', 'customer_digital_activity_13', 'customer_digital_activity_14', 'customer_digital_activity_15', 'customer_spend_15', 'customer_digital_activity_16', 'customer_spend_16', 'customer_spend_17', 'customer_digital_activity_17', 'customer_digital_activity_03', 'merchant_spend_11', 'customer_digital_activity_18', 'customer_digital_activity_19', 'distance_01', 'customer_digital_activity_20', 'distance_02', 'distance_03', 'customer_spend_18', 'customer_spend_19', 'customer_digital_activity_21', 'customer_digital_activity_22', 'distance_04', 'merchant_profile_02', 'merchant_spend_09', 'merchant_profile_03', 'customer_digital_activity_01', 'merchant_spend_10', 'customer_profile_03', 'customer_digital_activity_02', 'customer_profile_04', 'customer', 'merchant']
ind_recommended
activation